# Rev 0.1.0

[project]
name = "assetforge"
version = "0.1.0"
description = "Skeleton package for the AssetForge desktop application"
requires-python = ">=3.10"
dependencies = [
    "pyside6",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
