# Rev 1.2.0 - Distro

[project]
name = "assetforge"
version = "1.2.0"
description = "Skeleton package for the AssetForge desktop application"
requires-python = ">=3.10"
dependencies = [
    "pyside6",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
